apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodderingstalwart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dodderingstalwart
  template:
    metadata:
      labels:
        app: dodderingstalwart
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
      containers:
        - name: dodderingstalwart
          image: carllafong/dodderingstalwart:latest
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80

